### ISSUE TITLE
azure/logging: management group level activity logs

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-hub#121]
The kit module currently collects only Subscription-level activity logs. 

We should research and consider how we can add MG level activity logs as well

See e.g. https://sameeraman.github.io/blog/2021/06/20/mgauditlogs/

**Comment by florianow** [comment]
https://www.torivar.com/2022/08/17/azure-management-group-activity-log-diagnostic-settings-with-terraform/ littlebit newer this toturial and with terraform

**Comment by florianow** [comment]
`"message": "Entity testmg has changed the parent entity value from 00000000-000-0000-0000-00000000000 to colliedev-foundation",
`
log entries looks well
